services:
  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/devflow
    depends_on:
      - mongo

  runner:
    build: ./runner
    environment:
      - MONGODB_URI=mongodb://mongo:27017/devflow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
      - server

volumes:
  mongo_data:
